### ISSUE TITLE
Debug Symphony Auth-db error when running MarcToXML on laptop

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/ld4p-tracer-bullet-scripts#9]
An example of the error, using the `common-configure` branch on my laptop:
```
$ LD4P_SIRSI=/data/src/dlss/ld4l/ld4p-data \
   LD4P_RDF=/data/src/dlss/ld4l/ld4p-rdf \
   ./generate_marcxml_with_auth_uris.sh 

Searching for MARC files: /data/src/dlss/ld4l/ld4p-data/Dataload/LD4P/Marc
ERROR: Conversion failed
Exception in thread "main" java.lang.NullPointerException
	at org.stanford.AuthDBConnection.open(AuthDBConnection.java:21)
	at org.stanford.MarcToXML.conn(MarcToXML.java:91)
	at org.stanford.MarcToXML.main(MarcToXML.java:46)
```

**Comment by jgreben** [comment]
Is the `server.conf` file in the `src/main/resources` folder in your project? Line 21 is trying to get that properties file to find out the connection details.

**Comment by darrenleeweber** [comment]
Yes, it seems to be there, both the development working checkout and in the packaged JAR, i.e.
```
$  jar tf /data/src/dlss/ld4l/ld4p-data/bin/ld4p_converter.jar  | grep server.conf
main/resources/server.conf
```

**Comment by darrenleeweber** [comment]
This was resolved by removing a custom `<resources>` clause from the converter POM.
- details are in https://github.com/sul-dlss/ld4p-tracer-bullets/pull/48
